blank_issues_enabled: false
contact_links:
  - name: Ask a question in Discussions
    url: https://github.com/keyvanarasteh/IronSight/discussions
    about: For support requests, "how to" questions, or general discussion.
